import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getFirestore, collection, onSnapshot } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
let DATA={teams:[],players:[],matches:[],points:[]},matches=[],players=[],points=[];
const logoFallback='assets/hpl-logo.png';
const silhouette='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><rect width="240" height="240" fill="#102219"/><circle cx="120" cy="78" r="42" fill="#82968a"/><path d="M40 230c5-55 35-85 80-85s75 30 80 85" fill="#82968a"/></svg>');
async function loadSeed(){try{const r=await fetch('./data.json');DATA=await r.json();players=DATA.players||[];matches=DATA.matches||[];points=DATA.points||[];renderAll()}catch(e){console.error('Could not load data.json',e)}}
function renderTeams(){ $('#teamGrid').innerHTML=DATA.teams.map(t=>`<button class="team teamButton" data-team="${esc(t.id)}"><img src="${esc(t.logo)}" onerror="this.src='${logoFallback}'" alt="${esc(t.name)} logo"><div class="teamBody"><h3>${esc(t.name)}</h3><span class="pill">${(t.squad||[]).length} Squad Players</span><p>${esc(t.ground)}</p><b>Tap to View Squad →</b></div></button>`).join('');document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>openSquad(b.dataset.team)) }
function playerCard(p){return `<button class="card playerButton" data-player="${esc(p.id)}"><img src="${esc(p.photo||silhouette)}" onerror="this.src='${silhouette}'" alt="${esc(p.name)}"><div class="cardBody"><h3>${esc(p.name)}</h3><span class="pill">${esc(p.role||'Player')}</span><p>${esc(p.season11?.runs??0)} Season 11 runs · ${esc(p.season11?.wickets??0)} wickets</p><b>View Profile →</b></div></button>`}
function bindPlayerButtons(){document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.player))}
function openSquad(id){const t=DATA.teams.find(x=>x.id===id);if(!t)return;$('#squadTitle').textContent=t.name+' Squad';$('#squadGround').textContent='Home Ground · '+t.ground;const arr=(t.squad||[]).map(n=>players.find(p=>p.name.toLowerCase()===n.toLowerCase())).filter(Boolean);$('#squadGrid').innerHTML=arr.map(playerCard).join('');bindPlayerButtons();$('#squadSection').hidden=false;$('#squadSection').scrollIntoView({behavior:'smooth',block:'start'})}
$('#backTeams').onclick=()=>{$('#squadSection').hidden=true;$('#teams').scrollIntoView({behavior:'smooth'})};
function renderPlayers(){const q=($('#playerSearch').value||'').toLowerCase();$('#playerGrid').innerHTML=players.filter(p=>p.name.toLowerCase().includes(q)).map(playerCard).join('');bindPlayerButtons()}
function renderMatches(filter='all'){const arr=filter==='all'?matches:matches.filter(m=>(m.status||'Upcoming').toLowerCase()===filter.toLowerCase());$('#matchGrid').innerHTML=arr.length?arr.map(m=>`<button class="card matchButton" data-match="${esc(m.id)}"><img src="${esc(m.resultImage||logoFallback)}" onerror="this.src='${logoFallback}'"><div class="cardBody"><span class="pill">${esc(m.status||'Upcoming')}</span><h3>${esc(m.team1||'Team 1')} vs ${esc(m.team2||'Team 2')}</h3><p>${esc(m.date||'')}</p><b>${esc(m.resultText||m.winner||'Match details')}</b><p>${esc(m.score1||'—')} · ${esc(m.score2||'—')}</p></div></button>`).join(''):`<div class="empty"><h3>No matches added yet</h3><p>Completed and upcoming matches will appear here after you add them in Admin.</p><a class="btn" href="admin.html">Open Admin Panel</a></div>`;document.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>openMatch(b.dataset.match))}
function renderSeason(){const complete=matches.filter(m=>(m.status||'').toLowerCase()==='completed');$('#seasonCards').innerHTML=[['Matches Played',complete.length],['Players',players.length],['Teams',DATA.teams.length],['Season','11']].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');const p=points.length?points:DATA.teams.map(t=>({team:t.name,played:0,wins:0,losses:0,points:0}));$('#pointsBody').innerHTML=p.map(x=>`<tr><td>${esc(x.team)}</td><td>${x.played||0}</td><td>${x.wins||0}</td><td>${x.losses||0}</td><td>${x.points||0}</td></tr>`).join('')}
function openPlayer(id){const p=players.find(x=>x.id===id);if(!p)return;const h=p.hplCareer||{},s=p.season11||{},ipl=p.iplCareer||{};$('#modal').innerHTML=`<div class="dialog"><button class="close" data-close>✕ Close</button><div class="profileHead"><img src="${esc(p.photo||silhouette)}" onerror="this.src='${silhouette}'" alt="${esc(p.name)}"><div><span class="pill">PLAYER PROFILE</span><h2>${esc(p.name)}</h2><p>${esc(p.place||p.country||'')} · ${esc(p.role||'Player')}</p><p>Jersey No. ${esc(p.jersey||'—')}</p></div></div><h3>Playing Style</h3><div class="stats"><div class="stat"><small>Batting</small><b class="smallStat">${esc(p.batting||'—')}</b></div><div class="stat"><small>Bowling</small><b class="smallStat">${esc(p.bowling||'—')}</b></div></div><h3>HPL Career Stats</h3><div class="stats">${[['Matches',h.matches],['Runs',h.runs],['Average',h.avg],['50s',h.fifties],['100s',h.hundreds],['Best',h.best]].map(([k,v])=>`<div class="stat"><small>${k}</small><b>${v??'—'}</b></div>`).join('')}</div><h3>Season 11 Stats</h3><div class="stats"><div class="stat"><small>Runs</small><b>${s.runs??0}</b></div><div class="stat"><small>Wickets</small><b>${s.wickets??0}</b></div></div><h3>IPL Career Runs</h3><div class="stat"><b>${ipl.runs??'Not entered'}</b><small>${ipl.runs!=null?'IPL career runs':'No verified total saved yet'}</small></div></div>`;$('#modal').classList.remove('hidden');$('#modal [data-close]').onclick=closeModal}
function openMatch(id){const m=matches.find(x=>x.id===id);if(!m)return;$('#modal').innerHTML=`<div class="dialog"><button class="close" data-close>✕ Close</button><h2>${esc(m.team1)} vs ${esc(m.team2)}</h2><span class="pill">${esc(m.status||'Upcoming')}</span><div class="stats"><div class="stat"><small>${esc(m.team1)}</small><b>${esc(m.score1||'—')}</b></div><div class="stat"><small>${esc(m.team2)}</small><b>${esc(m.score2||'—')}</b></div></div><h3>${esc(m.resultText||m.winner||'Result not entered')}</h3>${m.resultImage?`<img src="${esc(m.resultImage)}" alt="Match result">`:''}${m.scorecard?`<pre>${esc(JSON.stringify(m.scorecard,null,2))}</pre>`:''}</div>`;$('#modal').classList.remove('hidden');$('#modal [data-close]').onclick=closeModal}
function closeModal(){$('#modal').classList.add('hidden')}$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#playerSearch').oninput=renderPlayers;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMatches(b.dataset.filter==='all'?'all':b.dataset.filter)});
function renderAll(){renderTeams();renderPlayers();renderMatches();renderSeason()}
// Splash is intentionally simple: progress to 100%, then require the user's tap to enter.
const bar=$('#loadbar'),txt=$('#loadtext'),tap=$('#tapopen');let n=0;const timer=setInterval(()=>{n=Math.min(100,n+5);bar.style.width=n+'%';txt.textContent='Loading '+n+'%';if(n===100){clearInterval(timer);txt.textContent='100% LOADED · WELCOME TO HPL';tap.hidden=false}},45);tap.onclick=()=>{$('#welcome').hidden=true;$('#site').hidden=false;window.scrollTo(0,0)};
await loadSeed();
try{const app=initializeApp(firebaseConfig),db=getFirestore(app);onSnapshot(collection(db,'hpl','data','players'),s=>{if(s.docs.length){const remote=s.docs.map(d=>({id:d.id,...d.data()}));players=mergePlayers(players,remote);renderPlayers();renderTeams()}},e=>console.warn('Firebase players unavailable; local squad remains visible',e));onSnapshot(collection(db,'hpl','data','matches'),s=>{if(s.docs.length){matches=s.docs.map(d=>({id:d.id,...d.data()}));renderMatches();renderSeason()}},e=>console.warn('Firebase matches unavailable; local site remains visible',e));onSnapshot(collection(db,'hpl','data','points'),s=>{if(s.docs.length){points=s.docs.map(d=>({id:d.id,...d.data()}));renderSeason()}},e=>console.warn('Firebase points unavailable; local points shown',e))}catch(e){console.warn('Firebase not initialized; showing bundled squad data',e)}
function mergePlayers(seed,remote){const map=new Map(seed.map(p=>[p.id,p]));for(const r of remote){const old=map.get(r.id)||map.get(r.name);map.set(r.id,{...(old||{}),...r})}return [...map.values()]}
